name: Go

on:
  push:
    branches: [ '*' ]  #executa em qualquer tipo de branch tanto nas pull quanto push request
  pull_request:
    branches: [ '*' ]

jobs:

  test:
    runs-on: ${{ matrix.os}} # roda em varios so diferentes e com varias versoes do GO com a estrategia de matrix
    env: # variaveis de ambiente para que a aplicação rode em qualquer ambiente
      HOST: localhost
      PORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
        go_version: ['1.18', '1.17', '>=1.18']
        os: ['ubuntu-latest',  'ubuntu-18.04']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
      
    - name: Build-DB
      run: docker-compose build
      
    - name: Create-DB
      run: docker-compose up -d

    - name: Test
      run: go test -v main_test.go 
      
  
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v main.go #compilamos o arquivo criado com o GO
      
    - name: Upload a Build Artifact #faz o upload do arquivo para que possa ser utilizado em outros workflows
      uses: actions/upload-artifact@v3.1.1
      with:
        # Artifact name
        name: programa
        # A file, directory or wildcard pattern that describes what to upload
        path: main
        # The desired behavior if no files are found using the provided      
  docker: # chama outro arquivo de rotina baseado no processo de build desse arquivo
    needs: build
    uses: ./.github/workflows/Docker.yml
    secrets: inherit
